In [48]:
import tensorflow as tf

In [16]:
a= tf.constant([2])
b= tf.constant([4])

In [17]:
add= tf.add(a,b)

In [26]:
session= tf.Session()
result= session.run(add)

In [29]:
print(result)

[6]


In [31]:
session.close()

In [34]:
with tf.Session() as ses:
    result= ses.run(add)
    print(result)

[6]


#### Multidimensional arrays using TensorFlow

In [42]:
scalar = tf.constant([1])
vector= tf.constant([1,2])
matrix= tf.constant([[1,2],[3,4],[5,6]])
tensor=tf.constant([ [[1,2,3],[4,5,6]] , [[7,8,9],[1,2,3]] , [[1,2,3],[4,5,6]] ])

with tf.Session() as session:
    
    r= session.run(scalar)
    print("Point:\n %s\n" % r)
    r= session.run(vector)
    print("Line:\n %s\n" % r)
    r= session.run(matrix)
    print("Surface:\n %s\n" % r)
    r= session.run(tensor)
    print("Volume:\n %s\n" % r)

Point:
 [1]

Line:
 [1 2]

Surface:
 [[1 2]
 [3 4]
 [5 6]]

Volume:
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]

 [[1 2 3]
  [4 5 6]]]



In [46]:
matrix_1= tf.constant([[1,2],[3,4],[5,6]])
matrix_2= tf.constant([[1,2],[3,4],[5,6]])

op1= tf.add(matrix_1,matrix_2)
op2= matrix_1 + matrix_2

with tf.Session() as session:
    
    r = session.run(op1)
    print("with tesnorflow add:\n %s"%r)
    
    r = session.run(op2)
    print("without tf add op:\n%s"% r)

with tesnorflow add:
 [[ 2  4]
 [ 6  8]
 [10 12]]
without tf add op:
[[ 2  4]
 [ 6  8]
 [10 12]]


#### Another TensorFlow function called tf.matmul()

In [47]:
matrix_1= tf.constant([[1,2],[3,4]])
matrix_2= tf.constant([[1,2],[3,4]])

op1= tf.matmul(matrix_1,matrix_2)

with tf.Session() as session:
    
    r = session.run(op1)
    print("with tesnorflow matmul:\n %s"%r)

with tesnorflow matmul:
 [[ 7 10]
 [15 22]]


#### Variables

In [77]:
var= tf.Variable(1)
con= tf.constant(4)
add= tf.add(var,con)
assign= tf.assign(var, add)

In [78]:
init= tf.global_variables_initializer()

In [83]:
with tf.Session() as session:
    
    session.run(init)
    
    for i in range(3):
        
        session.run(assign)
        print(session.run(var))

5
9
13
