## TensorFlow

The word tensor from new latin means "that which stretches". It is a mathematical object that is named tensor because an early application of tensors was the study of materials stretching under tension. The contemporary meaning of tensors can be taken as multidimensional arrays.

In TensorFlow all data is passed between operations in a computation graph, and these are passed in the form of Tensors, hence the name of TensorFlow. 

TensorFlow defines computations as Graphs, and these are made with operations (also know as “ops”). So, when we work with TensorFlow, it is the same as defining a series of operations in a Graph.


<img src='https://ibm.box.com/shared/static/a94cgezzwbkrq02jzfjjljrcaozu5s2q.png'>


In [102]:
import tensorflow as tf

In [84]:
a= tf.constant([2])
b= tf.constant([4])

In [17]:
add= tf.add(a,b)

In [90]:
session= tf.Session()
result= session.run(add)

In [91]:
print(result)

[4]


In [31]:
session.close()

In [34]:
with tf.Session() as ses:
    result= ses.run(add)
    print(result)

[6]


#### Multidimensional arrays using TensorFlow

In [42]:
scalar = tf.constant([1])
vector= tf.constant([1,2])
matrix= tf.constant([[1,2],[3,4],[5,6]])
tensor=tf.constant([ [[1,2,3],[4,5,6]] , [[7,8,9],[1,2,3]] , [[1,2,3],[4,5,6]] ])

with tf.Session() as session:
    
    r= session.run(scalar)
    print("Point:\n %s\n" % r)
    r= session.run(vector)
    print("Line:\n %s\n" % r)
    r= session.run(matrix)
    print("Surface:\n %s\n" % r)
    r= session.run(tensor)
    print("Volume:\n %s\n" % r)

Point:
 [1]

Line:
 [1 2]

Surface:
 [[1 2]
 [3 4]
 [5 6]]

Volume:
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]

 [[1 2 3]
  [4 5 6]]]



In [46]:
matrix_1= tf.constant([[1,2],[3,4],[5,6]])
matrix_2= tf.constant([[1,2],[3,4],[5,6]])

op1= tf.add(matrix_1,matrix_2)
op2= matrix_1 + matrix_2

with tf.Session() as session:
    
    r = session.run(op1)
    print("with tesnorflow add:\n %s"%r)
    
    r = session.run(op2)
    print("without tf add op:\n%s"% r)

with tesnorflow add:
 [[ 2  4]
 [ 6  8]
 [10 12]]
without tf add op:
[[ 2  4]
 [ 6  8]
 [10 12]]


#### Another TensorFlow function called tf.matmul()

In [47]:
matrix_1= tf.constant([[1,2],[3,4]])
matrix_2= tf.constant([[1,2],[3,4]])

op1= tf.matmul(matrix_1,matrix_2)

with tf.Session() as session:
    
    r = session.run(op1)
    print("with tesnorflow matmul:\n %s"%r)

with tesnorflow matmul:
 [[ 7 10]
 [15 22]]


### Variables

To define variables we use the command `tf.variable()`. To be able to use variables in a computation graph it is necessary to initialize them before running the graph in a session. This is done by running `tf.global_variables_initializer()`.

In [77]:
var= tf.Variable(1)
con= tf.constant(4)
add= tf.add(var,con)
assign= tf.assign(var, add)

In [78]:
init= tf.global_variables_initializer()

In [83]:
with tf.Session() as session:
    
    session.run(init)
    
    for i in range(3):
        
        session.run(assign)
        print(session.run(var))

5
9
13


### Placeholders

Placeholders can be seen as "holes" in your model, "holes" which you will pass the data to, you can create them using 
tf.placeholder(datatype), where datatype specifies the type of data (integers, floating points, strings, booleans) along with its precision (8, 16, 32, 64) bits.

In [93]:
a= tf.placeholder(tf.float32)
b=a*3

In [96]:
with tf.Session() as session:
    r= session.run(b, feed_dict={a:2})
    print(r)

6.0


In [98]:
d={a:[[1,2],[3,4]]}

with tf.Session() as session:
    r= session.run(b, feed_dict=d)
    print(r)

[[ 3.  6.]
 [ 9. 12.]]


### Operations

Operations are nodes that represent the mathematical operations over the tensors on a graph. These operations can be any kind of functions, like add and subtract tensor or maybe an activation function.

In [101]:
a= tf.constant([4])
b= tf.constant([2])
add= tf.add(a,b)
sub=tf.subtract(a,b)

with tf.Session() as ses:
    result= ses.run(add)
    print(result)
    
    result= ses.run(sub)
    print(result)

[6]
[2]
